[package]
name = "keyring"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
abi = { path = "../abi" }
hbd_core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
base64 = "0.22"
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_Security_Cryptography"] }